# example netlify.toml
[build]
  base = "frontend"
  command = "curl -fsSL https://bun.sh/install | bash && export BUN_INSTALL=/home/user/.bun && export PATH=$BUN_INSTALL/bin:$PATH && bun run build"
  publish = "dist"
  functions = "netlify/functions"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
    command = "bun dev" # Command to start your dev server
    port = 3000 # Port that the dev server will be listening on
    publish = "server" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
